# Generated by Django 5.2.8 on 2025-11-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('price_per_night', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('images_alt', models.JSONField(blank=True, default=list)),
                ('blurPlaceholder', models.CharField(blank=True, max_length=500)),
                ('rooms', models.JSONField(blank=True, default=list)),
                ('policies', models.JSONField(blank=True, default=dict)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('ideal_for', models.JSONField(blank=True, default=list)),
                ('distance_from_center_km', models.FloatField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('why_ai_picked', models.TextField(blank=True)),
                ('sdg_tags', models.JSONField(blank=True, default=list)),
                ('nearby', models.JSONField(blank=True, default=list)),
                ('sustainability', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
